export VENV=../venv/bin
export GITHUB_WEBHOOK_GIT_URL=https://api.github.com/repos/andrecp/json_db/contents/
export GITHUB_WEBHOOK_GIT_BRANCH=master
export GITHUB_WEBHOOK_GIT_PUSH_URL=https://fiery-inferno-4391.firebaseio.com/desks/
export GITHUB_WEBHOOK_WEBHOOK_WHITELIST=".json;files"
# WIP
export GITHUB_WEBHOOK_opendesk__collection_API_URL=https://opendesk-develop.herokuapp.com/api/v1
export GITHUB_WEBHOOK_opendesk__collection_SECRET_TOKEN=bearer_token generated by our api
export GITHUB_SECRET_TOKEN=your_token